---
- hosts: linux
  tasks:
  - name: print file content
    command: cat /home/centos/playbook/file1
    register: filecontent
  - debug: msg="File is empty"
    when: filecontent.stdout==""
  - debug: msg="File is not empty"
    when: filecontent.stdout!=""
