---
- hosts: linux
  vars:
    test: welcome to infinite
    Test: testing
  tasks:
  - name: print variable
    debug:
      msg: "{{test}}"
  - name: print another variable
    debug:
      msg: "{{Test}}"
